wandb_version: 1

learning_rate:
  desc: null
  value: 5.0e-05
train_batch_size:
  desc: null
  value: 8
pre_seq_leg:
  desc: null
  value: 128
max_source_length:
  desc: null
  value: 64
max_target_length:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706068136.550788
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 105
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.16.2
      6: 4.30.2
      8:
      - 5
      13: linux-x86_64
