wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.30.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705912479.134633
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 105
      3:
      - 23
      4: 3.10.13
      5: 0.16.2
      6: 4.30.2
      8:
      - 5
      13: linux-x86_64
output_dir:
  desc: null
  value: output/adgen-chatglm2-6b-pt-128-1e-3
overwrite_output_dir:
  desc: null
  value: true
do_train:
  desc: null
  value: false
do_eval:
  desc: null
  value: false
do_predict:
  desc: null
  value: true
evaluation_strategy:
  desc: null
  value: IntervalStrategy.NO
prediction_loss_only:
  desc: null
  value: false
per_device_train_batch_size:
  desc: null
  value: 1
per_device_eval_batch_size:
  desc: null
  value: 4
per_gpu_train_batch_size:
  desc: null
  value: null
per_gpu_eval_batch_size:
  desc: null
  value: null
gradient_accumulation_steps:
  desc: null
  value: 16
eval_accumulation_steps:
  desc: null
  value: null
eval_delay:
  desc: null
  value: 0
learning_rate:
  desc: null
  value: 0.001
weight_decay:
  desc: null
  value: 0.0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
num_train_epochs:
  desc: null
  value: 3.0
max_steps:
  desc: null
  value: 10
lr_scheduler_type:
  desc: null
  value: SchedulerType.LINEAR
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
log_level:
  desc: null
  value: passive
log_level_replica:
  desc: null
  value: warning
log_on_each_node:
  desc: null
  value: true
logging_dir:
  desc: null
  value: output/adgen-chatglm2-6b-pt-128-1e-3/runs/Jan22_16-34-27_marsen
logging_strategy:
  desc: null
  value: IntervalStrategy.STEPS
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 10
logging_nan_inf_filter:
  desc: null
  value: true
save_strategy:
  desc: null
  value: IntervalStrategy.STEPS
save_steps:
  desc: null
  value: 10
save_total_limit:
  desc: null
  value: null
save_safetensors:
  desc: null
  value: false
save_on_each_node:
  desc: null
  value: false
no_cuda:
  desc: null
  value: false
use_mps_device:
  desc: null
  value: false
seed:
  desc: null
  value: 42
data_seed:
  desc: null
  value: null
jit_mode_eval:
  desc: null
  value: false
use_ipex:
  desc: null
  value: false
bf16:
  desc: null
  value: false
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
half_precision_backend:
  desc: null
  value: auto
bf16_full_eval:
  desc: null
  value: false
fp16_full_eval:
  desc: null
  value: false
tf32:
  desc: null
  value: null
local_rank:
  desc: null
  value: 0
ddp_backend:
  desc: null
  value: null
tpu_num_cores:
  desc: null
  value: null
tpu_metrics_debug:
  desc: null
  value: false
debug:
  desc: null
  value: []
dataloader_drop_last:
  desc: null
  value: false
eval_steps:
  desc: null
  value: null
dataloader_num_workers:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
run_name:
  desc: null
  value: output/adgen-chatglm2-6b-pt-128-1e-3
disable_tqdm:
  desc: null
  value: false
remove_unused_columns:
  desc: null
  value: true
label_names:
  desc: null
  value: null
load_best_model_at_end:
  desc: null
  value: false
metric_for_best_model:
  desc: null
  value: null
greater_is_better:
  desc: null
  value: null
ignore_data_skip:
  desc: null
  value: false
sharded_ddp:
  desc: null
  value: []
fsdp:
  desc: null
  value: []
fsdp_min_num_params:
  desc: null
  value: 0
fsdp_config:
  desc: null
  value:
    fsdp_min_num_params: 0
    xla: false
    xla_fsdp_grad_ckpt: false
fsdp_transformer_layer_cls_to_wrap:
  desc: null
  value: null
deepspeed:
  desc: null
  value: null
label_smoothing_factor:
  desc: null
  value: 0.0
optim:
  desc: null
  value: OptimizerNames.ADAMW_HF
optim_args:
  desc: null
  value: null
adafactor:
  desc: null
  value: false
group_by_length:
  desc: null
  value: false
length_column_name:
  desc: null
  value: length
report_to:
  desc: null
  value:
  - wandb
ddp_find_unused_parameters:
  desc: null
  value: null
ddp_bucket_cap_mb:
  desc: null
  value: null
dataloader_pin_memory:
  desc: null
  value: true
skip_memory_metrics:
  desc: null
  value: true
use_legacy_prediction_loop:
  desc: null
  value: false
push_to_hub:
  desc: null
  value: false
resume_from_checkpoint:
  desc: null
  value: null
hub_model_id:
  desc: null
  value: null
hub_strategy:
  desc: null
  value: HubStrategy.EVERY_SAVE
hub_token:
  desc: null
  value: null
hub_private_repo:
  desc: null
  value: false
gradient_checkpointing:
  desc: null
  value: false
include_inputs_for_metrics:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
push_to_hub_model_id:
  desc: null
  value: null
push_to_hub_organization:
  desc: null
  value: null
push_to_hub_token:
  desc: null
  value: null
mp_parameters:
  desc: null
  value: ''
auto_find_batch_size:
  desc: null
  value: false
full_determinism:
  desc: null
  value: false
torchdynamo:
  desc: null
  value: null
ray_scope:
  desc: null
  value: last
ddp_timeout:
  desc: null
  value: 1800
torch_compile:
  desc: null
  value: false
torch_compile_backend:
  desc: null
  value: null
torch_compile_mode:
  desc: null
  value: null
xpu_backend:
  desc: null
  value: null
sortish_sampler:
  desc: null
  value: false
predict_with_generate:
  desc: null
  value: true
generation_max_length:
  desc: null
  value: 256
generation_num_beams:
  desc: null
  value: null
generation_config:
  desc: null
  value: null
distributed_state:
  desc: null
  value: 'Distributed environment: MULTI_GPU  Backend: nccl

    Num processes: 1

    Process index: 0

    Local process index: 0

    Device: cuda:0

    '
_n_gpu:
  desc: null
  value: 1
__cached__setup_devices:
  desc: null
  value: cuda:0
deepspeed_plugin:
  desc: null
  value: null
model_name_or_path:
  desc: null
  value: /home/ubuntu/Documents/ai/model/chatglm2-6b
ptuning_checkpoint:
  desc: null
  value: null
config_name:
  desc: null
  value: null
tokenizer_name:
  desc: null
  value: null
cache_dir:
  desc: null
  value: null
use_fast_tokenizer:
  desc: null
  value: true
model_revision:
  desc: null
  value: main
use_auth_token:
  desc: null
  value: false
resize_position_embeddings:
  desc: null
  value: null
quantization_bit:
  desc: null
  value: 8
pre_seq_len:
  desc: null
  value: 128
prefix_projection:
  desc: null
  value: false
lang:
  desc: null
  value: null
dataset_name:
  desc: null
  value: null
dataset_config_name:
  desc: null
  value: null
prompt_column:
  desc: null
  value: query
response_column:
  desc: null
  value: answer
history_column:
  desc: null
  value: null
train_file:
  desc: null
  value: ../data/train_less.json
validation_file:
  desc: null
  value: ../data/val_less.json
test_file:
  desc: null
  value: ../data/test.json
overwrite_cache:
  desc: null
  value: true
preprocessing_num_workers:
  desc: null
  value: 1
max_source_length:
  desc: null
  value: 64
max_target_length:
  desc: null
  value: 256
val_max_target_length:
  desc: null
  value: 256
pad_to_max_length:
  desc: null
  value: false
max_train_samples:
  desc: null
  value: null
max_eval_samples:
  desc: null
  value: null
max_predict_samples:
  desc: null
  value: null
num_beams:
  desc: null
  value: null
ignore_pad_token_for_loss:
  desc: null
  value: true
source_prefix:
  desc: null
  value: '请用最简洁的语言回答如下问题:'
forced_bos_token:
  desc: null
  value: null
